receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "internal-exporters"
          static_configs:
            - targets: ["HOST_A:9100", "HOST_B:9100"]
        - job_name: "app-metrics"
          static_configs:
            - targets: ["HOST_C:8080"]

  otlp:
    protocols:
      grpc:
      http

  jaeger:
    protocols:
      grpc:
      thrift_http

  zipkin:
    protocols:
      http

processors:
  batch: {}

exporters:
  prometheusremotewrite:
    endpoint: "http://<MIMIR_HOST>:9009/api/v1/push"
    insecure: true

  otlp/tempo:
    endpoint: "<TEMPO_HOST>:4317"
    tls:
      insecure: true

  loki:
    endpoint: "http://<LOKI_HOST>:3100/loki/api/v1/push"
    # If Loki requires auth:
    # basic_auth:
    #   username: "loki-user"
    #   password: "loki-pass"
    # Or: bearertoken: "/etc/loki-token.txt"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]

    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
