receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "internal-exporters"
          static_configs:
            - targets: ["HOST_A:9100", "HOST_B:9100"]
        - job_name: "app-metrics"
          static_configs:
            - targets: ["HOST_C:8080"]

  otlp:
    protocols:
      grpc: {}   # enable OTLP/gRPC on 4317
      http: {}   # enable OTLP/HTTP on 4318

  jaeger:
    protocols:
      grpc: {}         # Jaeger gRPC on 14250
      thrift_http: {}  # Jaeger HTTP (Thrift) on 14268

  zipkin:
    # Zipkin only needs a single endpoint; remove "protocols:" entirely
    endpoint: "0.0.0.0:9411"

processors:
  batch: {}

exporters:
  prometheusremotewrite:
    endpoint: "http://10.0.113.11:9009/api/v1/push"
    tls:
      insecure: true

  otlp/tempo:
    endpoint: "10.0.113.11:4317"
    tls:
      insecure: true

  loki:
    endpoint: "http://10.0.113.11:3100/loki/api/v1/push"
    # If Loki needs authentication, uncomment and fill in:
    # basic_auth:
    #   username: "loki-user"
    #   password: "loki-pass"
    # OR:
    # bearertoken: "/etc/loki-token.txt"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]

    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
